runtime: python27
api_version: 1
threadsafe: true
service: main

handlers:
- url: /static
  static_dir: static
  application_readable: true
  
- url: /admin/.*
  script: admin.app
  login: admin
  
- url: /.*
  script: main.app
#  login: admin
